set(SOURCE_FILES_make-dictionaries-readable
        ${CMAKE_CURRENT_SOURCE_DIR}/src/compressor_frontend/Buffer.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/compressor_frontend/Constants.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/compressor_frontend/finite_automata/RegexAST.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/compressor_frontend/finite_automata/RegexAST.tpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/compressor_frontend/finite_automata/RegexDFA.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/compressor_frontend/finite_automata/RegexDFA.tpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/compressor_frontend/finite_automata/RegexNFA.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/compressor_frontend/finite_automata/RegexNFA.tpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/compressor_frontend/finite_automata/UnicodeIntervalTree.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/compressor_frontend/finite_automata/UnicodeIntervalTree.tpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/compressor_frontend/InputBuffer.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/compressor_frontend/InputBuffer.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/compressor_frontend/LALR1Parser.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/compressor_frontend/LALR1Parser.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/compressor_frontend/LALR1Parser.tpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/compressor_frontend/Lexer.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/compressor_frontend/Lexer.tpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/compressor_frontend/LogParser.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/ src/compressor_frontend/LogParser.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/compressor_frontend/OutputBuffer.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/compressor_frontend/OutputBuffer.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/compressor_frontend/SchemaParser.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/compressor_frontend/SchemaParser.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/compressor_frontend/Token.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/compressor_frontend/Token.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/compressor_frontend/utils.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/compressor_frontend/utils.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/dictionary_utils.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/dictionary_utils.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/DictionaryEntry.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/DictionaryEntry.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/DictionaryReader.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/DictionaryReader.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/FileReader.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/FileReader.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/FileWriter.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/FileWriter.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/LogTypeDictionaryEntry.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/LogTypeDictionaryEntry.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/LogTypeDictionaryReader.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/LogTypeDictionaryReader.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/ParsedMessage.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/ParsedMessage.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/ReaderInterface.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/ReaderInterface.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/streaming_compression/Decompressor.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/streaming_compression/Decompressor.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/streaming_compression/passthrough/Decompressor.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/streaming_compression/passthrough/Decompressor.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/streaming_compression/zstd/Decompressor.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/streaming_compression/zstd/Decompressor.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Utils.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/Utils.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/utils/make_dictionaries_readable/CommandLineArguments.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/utils/make_dictionaries_readable/CommandLineArguments.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/utils/make_dictionaries_readable/make-dictionaries-readable.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/VariableDictionaryEntry.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/VariableDictionaryEntry.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/VariableDictionaryReader.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/VariableDictionaryReader.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/WriterInterface.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/WriterInterface.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/submodules/date/include/date/date.h
        )
add_executable(make-dictionaries-readable ${SOURCE_FILES_make-dictionaries-readable})
target_link_libraries(make-dictionaries-readable
        PRIVATE
        Boost::filesystem Boost::iostreams Boost::program_options
        spdlog::spdlog
        ZStd::ZStd
        )
target_compile_features(make-dictionaries-readable
        PRIVATE cxx_std_17
        )
